import 'package:flutter/material.dart';
import '../models/service_model.dart';

class LanguageProvider extends ChangeNotifier {
  String _selectedLanguage = 'TR';
  
  String get selectedLanguage => _selectedLanguage;

  void changeLanguage(String newLanguage) {
    if (newLanguage != _selectedLanguage) {
      _selectedLanguage = newLanguage;
      notifyListeners();
    }
  }

  List<Service> getServices() {
    return [
      Service(name: getTranslation('manicure'), description: getTranslation('manicure_desc'), price: 30.0, icon: Icons.content_cut),
      Service(name: getTranslation('pedicure'), description: getTranslation('pedicure_desc'), price: 40.0, icon: Icons.moped),
      Service(name: getTranslation('gel_polish'), description: getTranslation('gel_polish_desc'), price: 35.0, icon: Icons.color_lens),
      Service(name: getTranslation('nail_art'), description: getTranslation('nail_art_desc'), price: 15.0, icon: Icons.brush),
      Service(name: getTranslation('acrylic_nails'), description: getTranslation('acrylic_nails_desc'), price: 60.0, icon: Icons.handyman),
      Service(name: getTranslation('eyelash_lifting'), description: getTranslation('eyelash_lifting_desc'), price: 50.0, icon: Icons.remove_red_eye),
    ];
  }

  // Translation helper
  String getTranslation(String key) {
    final translations = {
      'TR': {
        'register': 'Kayıt',
        'login': 'Giriş',
        'new_collection': 'Yeni Koleksiyon',
        'stylish_designs': 'Şık ve Modern Nail Art Tasarımları',
        'special_discount': 'Özel İndirim',
        'discount_packages': '%40 İndirimli Nail Art Paketleri',
        'professional_service': 'Profesyonel Hizmet',
        'expert_team': 'Uzman Ekibimizle Güvenilir Hizmet',
        'my_profile': 'Profilim',
        'book_appointment': 'Randevu Al',
        'buy_product': 'Ürün Al',
        'services': 'Hizmetler',
        'new_tag': 'YENİ',
        'outlet_description': '800\'den Fazla Üründe',
        'outlet_discount': '%80\'e Kadar',
        'profile': 'Profil',
        'language_settings': 'Dil Ayarları',
        'select_language': 'Dil Seçin',
        'home': 'Ana Sayfa',
        'appointments': 'Randevular',
        'password': 'Şifre',
        'no_account': 'Hesabınız yok mu?',
        'personal_info': 'Kişisel Bilgiler',
        'personal_info_desc': 'Size özel deneyim için temel bilgilerinizi girin',
        'contact_info': 'İletişim Bilgileri',
        'contact_info_desc': 'Sizinle iletişim kurabilmemiz için bilgilerinizi girin',
        'account_info': 'Hesap Bilgileri',
        'account_info_desc': 'Güvenli hesabınız için giriş bilgilerinizi oluşturun',
        'name': 'Ad',
        'surname': 'Soyad',
        'birth_date': 'Doğum Tarihi',
        'phone': 'Telefon',
        'address': 'Adres',
        'city': 'Şehir',
        'confirm_password': 'Şifre Tekrarı',
        'accept_terms': 'Kullanım koşullarını kabul ediyorum',
        'previous': 'Önceki',
        'next': 'Sonraki',
        'complete_registration': 'Kayıt Ol',
        'name_required': 'Ad gerekli',
        'surname_required': 'Soyad gerekli',
        'birth_date_required': 'Doğum tarihi gerekli',
        'phone_required': 'Telefon gerekli',
        'address_required': 'Adres gerekli',
        'city_required': 'Şehir gerekli',
        'builder_system': 'Builder Sistem',
        'builder_system_desc': 'Profesyonel nail art için tamamlayıcı ürün sistemi',
        'travel_kit': 'Seyahat Kiti',
        'travel_kit_desc': 'Her yerde mükemmel nail care için compact çanta',
        'nail_art_collection': 'Nail Art Koleksiyonu',
        'nail_art_collection_desc': 'Renkli ve yaratıcı nail art tasarımları',
        'creative_designs': 'Yaratıcı tasarımlar ve sınırsız renk seçenekleri',
        'professional_quality': 'Profesyonel kalite ve uzun süre dayanıklılık',
        'book_appointment_title': 'Randevu Oluştur',
        'select_branch': 'Şube Seçin',
        'select_date': 'Tarih Seçin',
        'no_date_selected': 'Tarih seçilmedi',
        'select_time': 'Saat Seçin',
        'no_time_selected': 'Saat seçilmedi',
        'select_artist': 'Nail Artist Seçin',
        'select_technique': 'İstenen Teknik',
        'please_select': 'Lütfen bir seçim yapın',
        'confirm_appointment': 'Randevuyu Onayla',
        'appointment_request_received': 'Randevu talebiniz alındı!',
        'manicure': 'Manikür',
        'manicure_desc': 'El ve tırnak bakımı, oje uygulaması',
        'pedicure': 'Pedikür',
        'pedicure_desc': 'Ayak ve tırnak bakımı, oje uygulaması',
        'gel_polish': 'Kalıcı Oje',
        'gel_polish_desc': 'Uzun süre dayanan parlak oje uygulaması',
        'nail_art': 'Nail Art',
        'nail_art_desc': 'Özel tasarım ve süslemeler',
        'acrylic_nails': 'Protez Tırnak',
        'acrylic_nails_desc': 'Jel veya akrilik ile tırnak uzatma',
        'eyelash_lifting': 'Wimpernlifting',
        'eyelash_lifting_desc': 'Kirpiklere doğal ve kalıcı kıvrım kazandırma',
        'service_description': 'Hizmet Açıklaması',
        'available_branches': 'Mevcut Şubeler',
        'detailed_info': 'Detaylı Bilgi',
        'detailed_info_text': 'Bu hizmet, en kaliteli malzemeler kullanılarak uzman ekibimiz tarafından titizlikle uygulanır. Müşteri memnuniyeti odaklı yaklaşımımızla, size özel bir deneyim sunmayı hedefliyoruz. Uygulama süresi yaklaşık olarak 45-60 dakika sürmektedir.',
        'email': 'E-posta',
        'info_saved': 'Bilgiler kaydedildi!',
        'my_appointments': 'Randevularım',
        'past_appointments': 'Geçmiş Randevular',
        'view_past_appointments': 'Tamamlanan randevularınızı görüntüleyin',
        'my_nail_album': 'Tırnak Albümüm',
        'photo_gallery': 'Fotoğraf Galerisi',
        'manage_your_designs': 'Yaptırdığınız tasarımların fotoğraflarını yönetin',
        'pending': 'Bekleyenler',
        'approved': 'Onaylananlar',
        'rejected': 'Reddedilenler',
        'no_appointments_to_show': 'Burada gösterilecek randevu yok.',
        'no_approved_appointments': 'Onaylanmış randevunuz bulunmamaktadır.'
      },
      'DE': {
        'register': 'Registrieren',
        'login': 'Anmelden',
        'new_collection': 'Neue Kollektion',
        'stylish_designs': 'Elegante und Moderne Nail Art Designs',
        'special_discount': 'Sonderrabatt',
        'discount_packages': '40% Rabatt auf Nail Art Pakete',
        'professional_service': 'Professioneller Service',
        'expert_team': 'Zuverlässiger Service mit unserem Expertenteam',
        'my_profile': 'Mein Profil',
        'book_appointment': 'Termin Buchen',
        'buy_product': 'Produkt Kaufen',
        'services': 'Dienstleistungen',
        'new_tag': 'NEU',
        'outlet_description': 'Auf über 800 Produkte',
        'outlet_discount': 'Bis zu -80%',
        'profile': 'Profil',
        'language_settings': 'Spracheinstellungen',
        'select_language': 'Sprache Auswählen',
        'home': 'Startseite',
        'appointments': 'Termine',
        'password': 'Passwort',
        'no_account': 'Kein Konto?',
        'personal_info': 'Persönliche Informationen',
        'personal_info_desc': 'Geben Sie Ihre Grundinformationen für ein personalisiertes Erlebnis ein',
        'contact_info': 'Kontaktinformationen',
        'contact_info_desc': 'Geben Sie Ihre Daten ein, damit wir Sie kontaktieren können',
        'account_info': 'Kontoinformationen',
        'account_info_desc': 'Erstellen Sie Ihre Anmeldedaten für ein sicheres Konto',
        'name': 'Name',
        'surname': 'Nachname',
        'birth_date': 'Geburtsdatum',
        'phone': 'Telefon',
        'address': 'Adresse',
        'city': 'Stadt',
        'confirm_password': 'Passwort bestätigen',
        'accept_terms': 'Ich akzeptiere die Nutzungsbedingungen',
        'previous': 'Zurück',
        'next': 'Weiter',
        'complete_registration': 'Registrieren',
        'name_required': 'Name erforderlich',
        'surname_required': 'Nachname erforderlich',
        'birth_date_required': 'Geburtsdatum erforderlich',
        'phone_required': 'Telefon erforderlich',
        'address_required': 'Adresse erforderlich',
        'city_required': 'Stadt erforderlich',
        'builder_system': 'Builder System',
        'builder_system_desc': 'Komplettes Produktsystem für professionelle Nail Art',
        'travel_kit': 'Reise-Kit',
        'travel_kit_desc': 'Kompakte Tasche für perfekte Nagelpflege überall',
        'nail_art_collection': 'Nail Art Kollektion',
        'nail_art_collection_desc': 'Bunte und kreative Nail Art Designs',
        'creative_designs': 'Kreative Designs und unbegrenzte Farboptionen',
        'professional_quality': 'Professionelle Qualität und langanhaltende Haltbarkeit',
        'book_appointment_title': 'Termin Erstellen',
        'select_branch': 'Filiale Wählen',
        'select_date': 'Datum Wählen',
        'no_date_selected': 'Kein Datum ausgewählt',
        'select_time': 'Uhrzeit Wählen',
        'no_time_selected': 'Keine Uhrzeit ausgewählt',
        'select_artist': 'Nail Artist Wählen',
        'select_technique': 'Gewünschte Technik',
        'please_select': 'Bitte eine Auswahl treffen',
        'confirm_appointment': 'Termin Bestätigen',
        'appointment_request_received': 'Ihre Terminanfrage wurde erhalten!',
        'manicure': 'Maniküre',
        'manicure_desc': 'Hand- und Nagelpflege, Nagellackanwendung',
        'pedicure': 'Pediküre',
        'pedicure_desc': 'Fuß- und Nagelpflege, Nagellackanwendung',
        'gel_polish': 'Schellack',
        'gel_polish_desc': 'Langanhaltende, glänzende Nagellackanwendung',
        'nail_art': 'Nail Art',
        'nail_art_desc': 'Individuelle Designs und Verzierungen',
        'acrylic_nails': 'Nagelmodellage',
        'acrylic_nails_desc': 'Nagelverlängerung mit Gel oder Acryl',
        'eyelash_lifting': 'Wimpernlifting',
        'eyelash_lifting_desc': 'Natürlicher und dauerhafter Schwung für die Wimpern',
        'service_description': 'Servicebeschreibung',
        'available_branches': 'Verfügbare Filialen',
        'detailed_info': 'Detaillierte Informationen',
        'detailed_info_text': 'Dieser Service wird von unserem Expertenteam unter Verwendung hochwertigster Materialien sorgfältig durchgeführt. Mit unserem kundenorientierten Ansatz möchten wir Ihnen ein einzigartiges Erlebnis bieten. Die Anwendungsdauer beträgt ca. 45-60 Minuten.',
        'email': 'E-Mail',
        'info_saved': 'Informationen gespeichert!',
        'my_appointments': 'Meine Termine',
        'past_appointments': 'Vergangene Termine',
        'view_past_appointments': 'Abgeschlossene Termine anzeigen',
        'my_nail_album': 'Mein Nagelalbum',
        'photo_gallery': 'Fotogalerie',
        'manage_your_designs': 'Verwalten Sie die Fotos Ihrer Designs',
        'pending': 'Ausstehend',
        'approved': 'Genehmigt',
        'rejected': 'Abgelehnt',
        'no_appointments_to_show': 'Hier gibt es keine Termine zum Anzeigen.',
        'no_approved_appointments': 'Sie haben keine genehmigten Termine.'
      },
      'EN': {
        'register': 'Register',
        'login': 'Login',
        'new_collection': 'New Collection',
        'stylish_designs': 'Stylish and Modern Nail Art Designs',
        'special_discount': 'Special Discount',
        'discount_packages': '40% Off Nail Art Packages',
        'professional_service': 'Professional Service',
        'expert_team': 'Reliable Service with Our Expert Team',
        'my_profile': 'My Profile',
        'book_appointment': 'Book Appointment',
        'buy_product': 'Buy Product',
        'services': 'Services',
        'new_tag': 'NEW',
        'outlet_description': 'On Over 800 Products',
        'outlet_discount': 'Up to -80%',
        'profile': 'Profile',
        'language_settings': 'Language Settings',
        'select_language': 'Select Language',
        'home': 'Home',
        'appointments': 'Appointments',
        'password': 'Password',
        'no_account': 'No account?',
        'personal_info': 'Personal Information',
        'personal_info_desc': 'Enter your basic information for a personalized experience',
        'contact_info': 'Contact Information',
        'contact_info_desc': 'Enter your details so we can contact you',
        'account_info': 'Account Information',
        'account_info_desc': 'Create your login credentials for a secure account',
        'name': 'Name',
        'surname': 'Surname',
        'birth_date': 'Birth Date',
        'phone': 'Phone',
        'address': 'Address',
        'city': 'City',
        'confirm_password': 'Confirm Password',
        'accept_terms': 'I accept the terms and conditions',
        'previous': 'Previous',
        'next': 'Next',
        'complete_registration': 'Register',
        'name_required': 'Name required',
        'surname_required': 'Surname required',
        'birth_date_required': 'Birth date required',
        'phone_required': 'Phone required',
        'address_required': 'Address required',
        'city_required': 'City required',
        'builder_system': 'Builder System',
        'builder_system_desc': 'Complete product system for professional nail art',
        'travel_kit': 'Travel Kit',
        'travel_kit_desc': 'Compact bag for perfect nail care everywhere',
        'nail_art_collection': 'Nail Art Collection',
        'nail_art_collection_desc': 'Colorful and creative nail art designs',
        'creative_designs': 'Creative designs and unlimited color options',
        'professional_quality': 'Professional quality and long-lasting durability',
        'book_appointment_title': 'Create Appointment',
        'select_branch': 'Select Branch',
        'select_date': 'Select Date',
        'no_date_selected': 'No date selected',
        'select_time': 'Select Time',
        'no_time_selected': 'No time selected',
        'select_artist': 'Select Nail Artist',
        'select_technique': 'Requested Technique',
        'please_select': 'Please make a selection',
        'confirm_appointment': 'Confirm Appointment',
        'appointment_request_received': 'Your appointment request has been received!',
        'manicure': 'Manicure',
        'manicure_desc': 'Hand and nail care, polish application',
        'pedicure': 'Pedicure',
        'pedicure_desc': 'Foot and nail care, polish application',
        'gel_polish': 'Gel Polish',
        'gel_polish_desc': 'Long-lasting, glossy polish application',
        'nail_art': 'Nail Art',
        'nail_art_desc': 'Custom designs and decorations',
        'acrylic_nails': 'Acrylic Nails',
        'acrylic_nails_desc': 'Nail extension with gel or acrylic',
        'eyelash_lifting': 'Eyelash Lifting',
        'eyelash_lifting_desc': 'Natural and lasting curl for eyelashes',
        'service_description': 'Service Description',
        'available_branches': 'Available Branches',
        'detailed_info': 'Detailed Information',
        'detailed_info_text': 'This service is meticulously applied by our expert team using the highest quality materials. With our customer-focused approach, we aim to provide you with a unique experience. The application time is approximately 45-60 minutes.',
        'email': 'E-mail',
        'info_saved': 'Information saved!',
        'my_appointments': 'My Appointments',
        'past_appointments': 'Past Appointments',
        'view_past_appointments': 'View your completed appointments',
        'my_nail_album': 'My Nail Album',
        'photo_gallery': 'Photo Gallery',
        'manage_your_designs': 'Manage photos of your designs',
        'pending': 'Pending',
        'approved': 'Approved',
        'rejected': 'Rejected',
        'no_appointments_to_show': 'No appointments to show here.',
        'no_approved_appointments': 'You have no approved appointments.'
      }
    };
    
    return translations[_selectedLanguage]?[key] ?? key;
  }
}
