// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwhcHFozLviX8RSvQ-eTuA3F53mc9cn60',
    appId: '1:1041055813008:web:824ac2056b9ded9e4eb715',
    messagingSenderId: '1041055813008',
    projectId: 'emmi-nail-app',
    authDomain: 'emmi-nail-app.firebaseapp.com',
    storageBucket: 'emmi-nail-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk-kFHc34Y3Ye-tpcOjkCpYoBAN1H2k5s',
    appId: '1:1041055813008:android:5655537c67edd4e04eb715',
    messagingSenderId: '1041055813008',
    projectId: 'emmi-nail-app',
    storageBucket: 'emmi-nail-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9yghChemjLNpfLKdOkzwjKonpaIorcLQ',
    appId: '1:1041055813008:ios:e94b49d3b7e77e974eb715',
    messagingSenderId: '1041055813008',
    projectId: 'emmi-nail-app',
    storageBucket: 'emmi-nail-app.firebasestorage.app',
    iosBundleId: 'com.emminail.app.emmiNailApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-macos-api-key',
    appId: 'your-macos-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'emmi-nail-app',
    storageBucket: 'emmi-nail-app.appspot.com',
    iosBundleId: 'com.emmi.nail.app',
  );
}